- name: Setup PostgreSQL Primary-Replica
  hosts: all
  become: true
  vars:
    postgresql_version: "15"
    max_connections: "50"
    shared_buffers: "128MB"
    wal_level: "replica"
    max_wal_senders: "10"
  tasks:
    - name: Install PostgreSQL 15 repository
      yum_repository:
        name: pgdg15
        description: PostgreSQL 15 repository
        baseurl: https://download.postgresql.org/pub/repos/yum/15/redhat/rhel-7-x86_64
        gpgcheck: true
        enabled: true
        gpgkey: https://download.postgresql.org/pub/repos/yum/keys/RPM-GPG-KEY-PGDG

    - name: Install PostgreSQL
      yum:
        name: "postgresql15-server"
        state: present

    - name: Check if /var/lib/pgsql/data folder is empty before proceeding
      find:
        paths: '/var/lib/pgsql/data'
        file_type: any
      register: filesFound

    - name: Initialize PostgreSQL database
      command: /usr/bin/postgresql-setup initdb
      when: filesFound.matched == 0

    - debug:
        msg: 'The /var/lib/pgsql/data folder is empty. Proceeding.'
      when: filesFound.matched == 0
      
    - name: Configure max_connections
      lineinfile:
        path: "/var/lib/pgsql/data/postgresql.conf"
        regexp: "^#?max_connections ="
        line: "max_connections = 50"
      notify: restart postgresql

    - name: Configure shared_buffers
      lineinfile:
        path: "/var/lib/pgsql/data/postgresql.conf"
        regexp: "^#?shared_buffers ="
        line: "shared_buffers = 128MB"
      notify: restart postgresql

    - name: Configure wal_level
      lineinfile:
        path: "/var/lib/pgsql/data/postgresql.conf"
        regexp: "^#?wal_level ="
        line: "wal_level = replica"
      notify: restart postgresql

    - name: Configure max_wal_senders
      lineinfile:
        path: "/var/lib/pgsql/data/postgresql.conf"
        regexp: "^#?max_wal_senders ="
        line: "max_wal_senders = 10"
      notify: restart postgresql

  handlers:
    - name: restart postgresql
      service:
        name: postgresql
        state: restarted